### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by ZhangQuan-hub** [liuofficial/CD-UNet#1]
作者，您好！我拜读了您的论文Crossed Dual-branch U-Net for Hyperspectral Image Super-Resolution，论文中将代码开源在这里。我对您的工作非常感兴趣，希望能研究代码进一步学习。请问代码被删除了吗，github项目上只剩下一个readme文件？谢谢！

**Comment by liuofficial** [comment]
论文刚接收，代码整理中，这几天会上传。祝好！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月31日 13:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [liuofficial/CD-UNet] 求助 (Issue #1) |

作者，您好！我拜读了您的论文Crossed Dual-branch U-Net for Hyperspectral Image Super-Resolution，论文中将代码开源在这里。我对您的工作非常感兴趣，希望能研究代码进一步学习。请问代码被删除了吗，github项目上只剩下一个readme文件？谢谢！

**Comment by ZhangQuan-hub** [comment]
感谢您的代码！
